events {}

http {
  upstream nacos_cluster {
    server nacos1:8848;
    server nacos2:8848;
    server nacos3:8848;
  }

  server {
    listen 8848;

    location / {
      proxy_pass http://nacos_cluster;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
