events {}

stream {
  upstream nacos_grpc_cluster {
    server nacos1:9848;
  }

  server {
    listen 9848;
    proxy_pass nacos_grpc_cluster;
  }
}

http {
  upstream nacos_cluster {
    server nacos1:8848;
  }

  server {
    listen 8848;

    location / {
      proxy_pass http://nacos_cluster;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
